package com.Azat9011.MTranstelegrambot.botapi;

/**Возможные состояния бота
 *
 * @author Azat9011
 */

public enum BotState {
    BUSES_SEARCH,
    BUSES_SEARCH_STARTED,
    BUSES_SEARCH_FINISH,
    ASK_BUS_STATION_DEPART,
    ASK_BUS_STATION_ARRIVAL,
    ASK_DATE_DEPART,
    DATE_DEPART_RECEIVED,
    SHOW_MAIN_MENU,
    BUS_INFO_RESPONCE_AWAITING,
    SHOW_SUBSCRIPTIONS_MENU,
    SHOW_BUS_STATIONS_BOOK_MENU,
    BUS_STATIONS_SEARCH,
    ASK_BUS_STATION_NAMEPART,
    BUS_STATION_NAMEPART_RECEIVED,
    SHOW_HELP_MENU;
}
